### ISSUE TITLE
Can't run demo example

### ISSUE THREAD

**Issue by mougrim** [mailru/queue-processor#1]
Wrong server name:

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Queue processor pool not found for server mougrim-1215N' in /home/mougrim/Private/development/mougrim/queue-processor/src/Processor/AbstractProcessor.php:522
Stack trace:
#0 /home/mougrim/Private/development/mougrim/queue-processor/src/Processor/AbstractProcessor.php(413): MailRu\QueueProcessor\Processor\AbstractProcessor->reinitConfig()
#1 /home/mougrim/Private/development/mougrim/queue-processor/src/Processor/AbstractProcessor.php(105): MailRu\QueueProcessor\Processor\AbstractProcessor->reinit()
#2 /home/mougrim/Private/development/mougrim/queue-processor/bin/queue-processor.php(97): MailRu\QueueProcessor\Processor\AbstractProcessor->run()
#3 {main}
  thrown in /home/mougrim/Private/development/mougrim/queue-processor/src/Processor/AbstractProcessor.php on line 522
```

Logs dirrectory isn't created:

```
Warning: Error open /home/mougrim/Private/development/mougrim/queue-processor/demo/config/../shared/logs/queue-processor.log in /home/mougrim/Private/development/mougrim/queue-processor/vendor/mougrim/php-logger/src/Appender/AppenderStream.php on line 115
PHP Warning:  Error open /home/mougrim/Private/development/mougrim/queue-processor/demo/config/../shared/logs/queue-processor.log in /home/mougrim/Private/development/mougrim/queue-processor/vendor/mougrim/php-logger/src/Appender/AppenderStream.php on line 115
```

**Comment by Erliz** [comment]
And how to fix other configs? May be use `localhost` for demo purpose?

**Comment by Erliz** [comment]
🆗
